# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e58b68cd2a4df625b3d8a2c9737bef4bb87196d04c6e95410a24b031fdaf6aa7eb6cb3f7a2eed83125ed2af12dacb57dc6f31a3e0995069584f135c9450f77bd

test:
  secret_key_base: 2de934f09680927a5c8aef64e07d66e5ac6cbc7b30174f8eb3eb7a290c78364fdbd6232aac006f313d30f83f6752d2ffbb4dee10c3d177a9e96e2386e47d0ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
